services:
  postgres:
    container_name: dock-Nbnb
    image: 'postgres:13.16'
    environment:
      POSTGRES_DB: nbnb
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: salman
    ports:
      - '5432:5432'
    volumes:
      - data_nbnb1:/var/lib/postgresql/data
volumes:
  data_nbnb1:
