services:
  postgres:
    image: 'postgres:13.16'
    environment:
      POSTGRES_DB: nbnb
      POSTGRES_PASSWORD: secret'
      POSTGRES_USER: salman
    ports:
      - '5432'
    volumes:
      - data_nbnb:/var/lib/postgresql/data
volumes:  
  data_nbnb:
